package GUI;

import LOGICA.GestorPrograma;
import LOGICA.LectorArchivo;
import LOGICA.Reportes;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

public class Pantalla extends javax.swing.JFrame {

    GestorPrograma gestorTexto;
    Reportes reportes = new Reportes();

    public Pantalla() {
        initComponents();
        btnOtrosReportes.setVisible(false);
        //btnReporteLexico.setVisible(false);
        //btnReporteSintactico.setVisible(false);
        btnGenerarGrafico.setVisible(false);

        gestorTexto = new GestorPrograma(txtPanel, jTextPane1, btnOtrosReportes, btnReporteSintactico, btnGenerarGrafico);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido5 = new javax.swing.JPanel();
        btnAnalizar = new javax.swing.JButton();
        btnReporteLexico = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGenerarGrafico = new javax.swing.JButton();
        btnReporteSintactico = new javax.swing.JButton();
        btnOtrosReportes = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane1 = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        btnReporteLexico.setText("Errores Léxicos");
        btnReporteLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteLexicoActionPerformed(evt);
            }
        });

        jButton1.setText("Archivo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnGenerarGrafico.setText("Generar Gráfico");
        btnGenerarGrafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarGraficoActionPerformed(evt);
            }
        });

        btnReporteSintactico.setText("Errores Sintácticos");
        btnReporteSintactico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteSintacticoActionPerformed(evt);
            }
        });

        btnOtrosReportes.setText("Otros Reportes");
        btnOtrosReportes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOtrosReportesActionPerformed(evt);
            }
        });

        txtPanel.setMaximumSize(new java.awt.Dimension(62, 22));
        jScrollPane2.setViewportView(txtPanel);

        jTextPane1.setMaximumSize(new java.awt.Dimension(62, 22));
        jScrollPane1.setViewportView(jTextPane1);

        javax.swing.GroupLayout contenido5Layout = new javax.swing.GroupLayout(contenido5);
        contenido5.setLayout(contenido5Layout);
        contenido5Layout.setHorizontalGroup(
            contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47))
            .addGroup(contenido5Layout.createSequentialGroup()
                .addGap(96, 96, 96)
                .addGroup(contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenido5Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(btnGenerarGrafico)
                        .addGap(49, 49, 49)
                        .addComponent(btnReporteLexico)
                        .addGap(47, 47, 47)
                        .addComponent(btnReporteSintactico)
                        .addGap(58, 58, 58)
                        .addComponent(btnOtrosReportes))
                    .addComponent(btnAnalizar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenido5Layout.setVerticalGroup(
            contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenido5Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(contenido5Layout.createSequentialGroup()
                        .addGroup(contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnReporteLexico)
                            .addComponent(jButton1)
                            .addComponent(btnGenerarGrafico)
                            .addComponent(btnReporteSintactico)
                            .addComponent(btnOtrosReportes))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 599, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(btnAnalizar)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(contenido5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(contenido5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:

        if (!txtPanel.getText().isBlank()) {

            btnReporteLexico.setVisible(true);
            gestorTexto.procesar(txtPanel.getText()/*, txtPanel, jTextPane1, btnOtrosReportes, btnReporteSintactico, btnGenerarGrafico*/);

        } else {
            JOptionPane.showMessageDialog(null, "No hay elementos ingresados", "ERROR", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnReporteLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteLexicoActionPerformed
        // TODO add your handling code here:
        reportes = new Reportes();
        reportes.reporte("ERRORESTokens", gestorTexto.getErroresLexico(), 4);
        //gestorTexto.reporteTokens();

    }//GEN-LAST:event_btnReporteLexicoActionPerformed

    private void btnReporteSintacticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteSintacticoActionPerformed
        // TODO add your handling code here:
        //reportes.reporte("Sintacticos", ERRORESSINTACTICOS, 5);
        reportes = new Reportes();
        if ((gestorTexto.getAnalizadorDDL() == null)) {
            reportes.mostrarTabla();
        } else {
            reportes.reporte("ERRORESSintactico", gestorTexto.getAnalizadorDDL().getErroresSintacticos(), 5);
        }
    }//GEN-LAST:event_btnReporteSintacticoActionPerformed

    private void btnOtrosReportesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOtrosReportesActionPerformed
        // TODO add your handling code here:
        reportes = new Reportes();
        reportes.setTodosLosComandos(gestorTexto.getAnalizadorDDL().getTodosLosComandos());
        reportes.obtenerOtrosReportes();

    }//GEN-LAST:event_btnOtrosReportesActionPerformed

    private void btnGenerarGraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarGraficoActionPerformed
        // TODO add your handling code here:
        gestorTexto.generarGrafico();
    }//GEN-LAST:event_btnGenerarGraficoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        LectorArchivo lector = new LectorArchivo(gestorTexto);
        lector.abrirArchivo();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnGenerarGrafico;
    private javax.swing.JButton btnOtrosReportes;
    private javax.swing.JButton btnReporteLexico;
    private javax.swing.JButton btnReporteSintactico;
    private javax.swing.JPanel contenido5;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JTextPane txtPanel;
    // End of variables declaration//GEN-END:variables
}
