package GUI;

import LOGICA.GestorTexto;
import LOGICA.Reportes;
import java.awt.Color;
import java.awt.Font;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.text.BadLocationException;
import javax.swing.text.SimpleAttributeSet;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;

public class Pantalla extends javax.swing.JFrame {

    LineNumberTextAreaTest lineNumber;
    GestorTexto gestorTexto = new GestorTexto();

    public Pantalla() {
        initComponents();
        this.lineNumber = new LineNumberTextAreaTest(texto);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contenido5 = new javax.swing.JPanel();
        texto = new javax.swing.JScrollPane();
        btnGenerarHTML = new javax.swing.JButton();
        btnAnalizar = new javax.swing.JButton();
        btnReporteTokens = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btnGenerarGraficas = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPanel = new javax.swing.JTextPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnGenerarHTML.setText("Generar HTML");
        btnGenerarHTML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerarHTMLActionPerformed(evt);
            }
        });

        btnAnalizar.setText("Analizar");
        btnAnalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnalizarActionPerformed(evt);
            }
        });

        btnReporteTokens.setText("Reportes");
        btnReporteTokens.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteTokensActionPerformed(evt);
            }
        });

        jButton1.setText("Archivo");

        btnGenerarGraficas.setText("Generar Gráfica");

        jScrollPane2.setViewportView(txtPanel);

        javax.swing.GroupLayout contenido5Layout = new javax.swing.GroupLayout(contenido5);
        contenido5.setLayout(contenido5Layout);
        contenido5Layout.setHorizontalGroup(
            contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contenido5Layout.createSequentialGroup()
                .addGroup(contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenido5Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jButton1)
                        .addGap(64, 64, 64)
                        .addComponent(btnGenerarGraficas)
                        .addGap(59, 59, 59)
                        .addComponent(btnGenerarHTML)
                        .addGap(47, 47, 47)
                        .addComponent(btnReporteTokens))
                    .addGroup(contenido5Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(btnAnalizar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(178, 178, 178))
            .addGroup(contenido5Layout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 722, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        contenido5Layout.setVerticalGroup(
            contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, contenido5Layout.createSequentialGroup()
                .addGroup(contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(contenido5Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addGroup(contenido5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnGenerarHTML)
                            .addComponent(btnReporteTokens)
                            .addComponent(jButton1)
                            .addComponent(btnGenerarGraficas)))
                    .addGroup(contenido5Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(texto, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(116, 116, 116)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(btnAnalizar)
                .addGap(25, 25, 25))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contenido5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 25, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contenido5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAnalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnalizarActionPerformed
        // TODO add your handling code here:

        if (!txtPanel.getText().isBlank()) {
            
            
            gestorTexto.procesar(txtPanel.getText(), txtPanel);

            


        } else {
            JOptionPane.showMessageDialog(null, "No hay elementos ingresados", "ERROR", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnAnalizarActionPerformed

    private void btnReporteTokensActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteTokensActionPerformed
        // TODO add your handling code here:

        gestorTexto.reporteTokens();

    }//GEN-LAST:event_btnReporteTokensActionPerformed

    private void btnGenerarHTMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerarHTMLActionPerformed
        if (!lineNumber.getText().isBlank()) {
            gestorTexto.generarHTML();
        } else {
            JOptionPane.showMessageDialog(null, "No hay elementos ingresados", "ERROR", JOptionPane.PLAIN_MESSAGE);
        }
    }//GEN-LAST:event_btnGenerarHTMLActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnalizar;
    private javax.swing.JButton btnGenerarGraficas;
    private javax.swing.JButton btnGenerarHTML;
    private javax.swing.JButton btnReporteTokens;
    private javax.swing.JPanel contenido5;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane texto;
    private javax.swing.JTextPane txtPanel;
    // End of variables declaration//GEN-END:variables
}
