// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: /home/debian/Desktop/GitProyectoFinalLF/ProyectoFinalLF/src/main/java/LOGICA/lexico.flex

package com.yeferal.main;

//Seccion de imports
import java.util.ArrayList;
import java.util.List;
import LOGICA.Token;
import java.awt.Color;



@SuppressWarnings("fallthrough")
public class AnalizadorLexico {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0, 0
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\10\0\2\1\1\2\2\3\1\1\22\0\1\4\1\5"+
    "\1\6\4\5\1\7\2\10\2\11\1\10\1\12\1\13"+
    "\1\11\1\14\1\15\1\16\1\17\6\20\1\21\1\22"+
    "\1\23\1\24\1\23\2\5\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\35\1\36\1\37\1\40"+
    "\1\41\1\42\1\43\1\44\1\45\1\46\1\47\1\50"+
    "\1\51\1\52\1\53\1\54\1\55\5\56\1\57\1\56"+
    "\32\57\1\5\1\60\2\5\6\0\1\3\133\0\1\56"+
    "\7\0\1\56\3\0\1\56\5\0\1\56\6\0\1\56"+
    "\u011d\0\1\61\1\62\16\0\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\1\1\5\2\6"+
    "\1\7\1\10\25\1\1\11\5\0\1\10\3\0\1\12"+
    "\3\0\1\12\23\0\1\13\14\0\1\14\2\0\1\15"+
    "\1\16\1\0\1\13\1\17\56\0\1\20\13\0\1\21"+
    "\11\0\1\12\33\0\1\22";

  private static int [] zzUnpackAction() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\63\0\63\0\63\0\63\0\146\0\63\0\63"+
    "\0\231\0\314\0\377\0\u0132\0\u0165\0\u0198\0\u01cb\0\u01fe"+
    "\0\u0231\0\u0264\0\u0297\0\u02ca\0\u02fd\0\u0330\0\u0363\0\u0396"+
    "\0\u03c9\0\u03fc\0\u042f\0\u0462\0\u0495\0\u04c8\0\u04fb\0\u052e"+
    "\0\u0561\0\u0594\0\u05c7\0\u05fa\0\u062d\0\u0660\0\63\0\u0693"+
    "\0\u06c6\0\u06f9\0\u072c\0\u075f\0\u0792\0\u07c5\0\63\0\u07f8"+
    "\0\u082b\0\u085e\0\u0891\0\u08c4\0\u08f7\0\u092a\0\u095d\0\u0990"+
    "\0\u09c3\0\u09f6\0\u0a29\0\u0a5c\0\u0a8f\0\u0ac2\0\u0af5\0\u0b28"+
    "\0\u0b5b\0\u0b8e\0\u0bc1\0\u0bf4\0\u0c27\0\u0c5a\0\u0c8d\0\u0cc0"+
    "\0\u0cf3\0\u0d26\0\u0d59\0\u0d8c\0\u0dbf\0\u0df2\0\u0e25\0\63"+
    "\0\u0e58\0\u0e8b\0\u0ebe\0\u0660\0\u0ef1\0\63\0\63\0\u0f24"+
    "\0\u0f57\0\u0f8a\0\u0fbd\0\u0ff0\0\u1023\0\u1056\0\u1089\0\u10bc"+
    "\0\u10ef\0\u072c\0\u1122\0\u1155\0\u1188\0\u11bb\0\u11ee\0\u1221"+
    "\0\u1254\0\u1287\0\u12ba\0\u12ed\0\u1320\0\u1353\0\u1386\0\u13b9"+
    "\0\u13ec\0\u141f\0\u1452\0\u1485\0\u14b8\0\u14eb\0\u151e\0\u1551"+
    "\0\u1584\0\u15b7\0\u15ea\0\u161d\0\u1650\0\u1683\0\u16b6\0\u16e9"+
    "\0\u171c\0\u174f\0\u1782\0\u17b5\0\u17e8\0\63\0\u181b\0\u184e"+
    "\0\u1881\0\u18b4\0\u18e7\0\u191a\0\u194d\0\u1980\0\u19b3\0\u19e6"+
    "\0\u1a19\0\63\0\u1a4c\0\u1a7f\0\u1ab2\0\u1ae5\0\u1b18\0\u1b4b"+
    "\0\u1b7e\0\u1bb1\0\u1be4\0\u1c17\0\u1c4a\0\u1c7d\0\u1cb0\0\u1ce3"+
    "\0\u1d16\0\u1d49\0\u1c17\0\u1d7c\0\u1daf\0\u1de2\0\u1e15\0\u1e48"+
    "\0\u1e7b\0\u1eae\0\u1ee1\0\u1f14\0\u1f47\0\u1f7a\0\u1fad\0\u1fe0"+
    "\0\u2013\0\u2046\0\u2079\0\u20ac\0\u20df\0\u2112\0\u2145\0\63";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\4\2\2\1\6\1\7"+
    "\1\10\1\11\1\7\5\12\1\2\1\7\1\13\1\7"+
    "\1\14\1\15\1\16\1\17\1\20\1\21\1\22\1\2"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\2\1\33\1\34\1\35\1\36\1\37\1\40\3\2"+
    "\1\41\1\2\1\6\1\2\70\0\1\42\1\43\1\0"+
    "\4\42\5\44\2\0\36\42\6\0\1\45\71\0\1\46"+
    "\5\12\36\0\1\41\27\0\1\47\66\0\1\50\7\0"+
    "\1\51\1\0\1\52\4\0\1\53\2\0\1\54\45\0"+
    "\1\55\5\0\1\56\11\0\1\57\32\0\1\60\15\0"+
    "\1\61\2\0\1\62\41\0\1\63\3\0\1\64\14\0"+
    "\1\65\70\0\1\66\33\0\1\67\15\0\1\70\2\0"+
    "\1\71\62\0\1\72\46\0\1\57\7\0\1\73\63\0"+
    "\1\74\50\0\1\75\66\0\1\76\52\0\1\77\7\0"+
    "\1\100\70\0\1\101\5\0\1\102\53\0\1\57\3\0"+
    "\1\103\62\0\1\104\45\0\1\105\62\0\1\106\17\0"+
    "\1\107\36\0\1\110\3\0\1\111\14\0\1\112\6\0"+
    "\1\113\47\0\1\114\1\0\1\115\43\0\1\116\71\0"+
    "\1\117\42\0\5\41\36\0\1\41\7\0\2\42\1\43"+
    "\1\120\11\42\2\0\36\42\1\0\1\120\60\0\1\121"+
    "\6\0\2\42\1\43\1\120\4\42\5\122\2\0\36\42"+
    "\1\0\1\120\12\0\1\123\64\0\5\124\72\0\1\57"+
    "\102\0\1\125\42\0\1\126\61\0\1\57\66\0\1\127"+
    "\62\0\1\130\72\0\1\131\66\0\1\132\53\0\1\133"+
    "\1\0\1\134\6\0\1\135\42\0\1\136\101\0\1\137"+
    "\41\0\1\140\10\0\1\141\6\0\1\142\56\0\1\143"+
    "\54\0\1\144\65\0\1\145\70\0\1\146\57\0\1\147"+
    "\62\0\1\150\66\0\1\151\1\152\47\0\1\153\102\0"+
    "\1\57\46\0\1\154\75\0\1\127\50\0\1\127\70\0"+
    "\1\126\52\0\1\155\1\156\51\0\1\125\67\0\1\157"+
    "\57\0\1\160\70\0\1\161\5\0\1\162\1\0\1\57"+
    "\53\0\1\127\47\0\1\163\110\0\1\164\57\0\1\165"+
    "\55\0\1\166\53\0\1\167\55\0\1\136\72\0\1\170"+
    "\5\0\1\171\45\0\1\172\52\0\1\173\45\0\2\42"+
    "\1\43\1\120\4\42\5\174\2\0\36\42\1\0\1\120"+
    "\4\0\1\123\7\0\5\123\4\0\33\123\34\0\1\175"+
    "\66\0\1\176\65\0\1\177\51\0\1\200\104\0\1\201"+
    "\60\0\1\202\55\0\1\203\45\0\1\204\62\0\1\205"+
    "\3\0\1\206\66\0\1\207\56\0\1\204\75\0\1\57"+
    "\65\0\1\210\62\0\1\165\44\0\1\211\72\0\1\57"+
    "\72\0\1\143\42\0\1\212\62\0\1\213\11\0\1\57"+
    "\61\0\1\57\55\0\1\214\65\0\1\57\53\0\1\215"+
    "\72\0\1\216\52\0\1\217\62\0\1\220\66\0\1\221"+
    "\65\0\1\166\72\0\1\206\43\0\1\222\62\0\1\57"+
    "\76\0\1\223\66\0\1\224\40\0\1\225\101\0\1\166"+
    "\74\0\1\226\6\0\2\42\1\43\1\120\4\42\5\227"+
    "\2\0\36\42\1\0\1\120\46\0\1\57\56\0\1\164"+
    "\51\0\1\230\56\0\1\231\76\0\1\153\71\0\1\232"+
    "\62\0\1\127\62\0\1\166\40\0\1\233\75\0\1\221"+
    "\71\0\1\234\47\0\1\235\73\0\1\214\47\0\1\236"+
    "\77\0\1\57\60\0\1\237\41\0\1\240\103\0\1\241"+
    "\43\0\1\214\60\0\1\242\106\0\1\166\42\0\1\243"+
    "\65\0\1\244\50\0\1\245\44\0\2\42\1\43\1\120"+
    "\2\42\1\246\6\42\2\0\36\42\1\0\1\120\25\0"+
    "\1\247\65\0\1\166\100\0\1\250\41\0\1\251\104\0"+
    "\1\57\46\0\1\153\60\0\1\252\66\0\1\253\73\0"+
    "\1\75\45\0\1\254\71\0\1\206\47\0\1\252\115\0"+
    "\1\42\6\0\2\42\1\43\1\120\4\42\1\255\1\256"+
    "\3\42\2\0\36\42\1\0\1\120\42\0\1\206\45\0"+
    "\1\257\104\0\1\166\61\0\1\206\43\0\1\206\75\0"+
    "\1\260\24\0\2\42\1\43\1\120\5\42\4\261\2\0"+
    "\36\42\1\0\1\120\4\0\2\42\1\43\1\120\4\42"+
    "\3\261\2\42\2\0\36\42\1\0\1\120\35\0\1\262"+
    "\54\0\1\224\37\0\2\42\1\43\1\120\2\42\1\263"+
    "\6\42\2\0\36\42\1\0\1\120\42\0\1\214\24\0"+
    "\2\42\1\43\1\120\4\42\1\264\2\265\1\266\1\42"+
    "\2\0\36\42\1\0\1\120\4\0\2\42\1\43\1\120"+
    "\5\42\4\267\2\0\36\42\1\0\1\120\4\0\2\42"+
    "\1\43\1\120\4\42\5\267\2\0\36\42\1\0\1\120"+
    "\4\0\2\42\1\43\1\120\4\42\2\267\3\42\2\0"+
    "\36\42\1\0\1\120\4\0\2\42\1\43\1\270\11\42"+
    "\2\0\36\42\1\0\1\270";

  private static int [] zzUnpacktrans() {
    int [] result = new int[8568];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\4\11\1\1\2\11\31\1\5\0\1\11\3\0"+
    "\1\1\3\0\1\11\23\0\1\1\14\0\1\11\2\0"+
    "\2\1\1\0\2\11\56\0\1\11\13\0\1\11\11\0"+
    "\1\1\33\0\1\11";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[184];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  @SuppressWarnings("unused")
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */

// Codigo Java

    private List<Token> lista = new ArrayList<>();
    private List<Token> listaErrores = new ArrayList<>();
    private List<Token> listaColores = new ArrayList<>();
    private Color MORADO = new Color(192, 0, 255);

    public List<Token> getLista(){
        return lista;
    }
    
    public List<Token> getListaErrores(){
        return listaErrores;
    }

    public List<Token> getListaColores() {
        return listaColores;
    }



  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public AnalizadorLexico(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public int yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is
        // (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof)
            zzPeek = false;
          else
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
        return YYEOF;
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { Token token = new Token(yytext(), "ERROR", yyline + 1, yycolumn + 1, Color.BLACK); 
                                                                                listaErrores.add(token); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 19: break;
          case 2:
            { /*Ignore*/
            }
          // fall through
          case 20: break;
          case 3:
            { Token token = new Token(yytext(), "ESPACIO", yyline + 1, yycolumn + 1, Color.BLACK); listaColores.add(token);
            }
          // fall through
          case 21: break;
          case 4:
            { System.out.print(yytext());
            }
          // fall through
          case 22: break;
          case 5:
            { Token token = new Token(yytext(), "SIGNOS", yyline + 1, yycolumn + 1, Color.BLACK); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 23: break;
          case 6:
            { Token token = new Token(yytext(), "ARITMETICOS", yyline + 1, yycolumn + 1, Color.BLACK); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 24: break;
          case 7:
            { Token token = new Token(yytext(), "ENTERO", yyline + 1, yycolumn + 1, Color.BLUE); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 25: break;
          case 8:
            { Token token = new Token(yytext(), "RELACIONALES", yyline + 1, yycolumn + 1, Color.BLACK); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 26: break;
          case 9:
            { Token token = new Token(yytext(), "IDENTIFICADOR", yyline + 1, yycolumn + 1, Color.MAGENTA); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 27: break;
          case 10:
            { Token token = new Token(yytext(), "CREATE", yyline + 1, yycolumn + 1, Color.ORANGE); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 28: break;
          case 11:
            { Token token = new Token(yytext(), "LOGICOS", yyline + 1, yycolumn + 1, Color.ORANGE); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 29: break;
          case 12:
            { Token token = new Token(yytext(), "CADENA", yyline + 1, yycolumn + 1, Color.GREEN); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 30: break;
          case 13:
            { Token token = new Token(yytext(), "COMENTARIO", yyline + 1, yycolumn + 1, Color.GRAY); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 31: break;
          case 14:
            { Token token = new Token(yytext(), "DECIMAL", yyline + 1, yycolumn + 1, Color.BLUE); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 32: break;
          case 15:
            { Token token = new Token(yytext(), "FUNCION AGREGACION", yyline + 1, yycolumn + 1, Color.BLUE); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 33: break;
          case 16:
            { Token token = new Token(yytext(), "TIPO DE DATO", yyline + 1, yycolumn + 1, MORADO); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 34: break;
          case 17:
            { Token token = new Token(yytext(), "BOOLEANO", yyline + 1, yycolumn + 1, Color.BLUE); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 35: break;
          case 18:
            { Token token = new Token(yytext(), "FECHA", yyline + 1, yycolumn + 1, Color.YELLOW); lista.add(token); listaColores.add(token);
            }
          // fall through
          case 36: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }

  /**
   * Runs the scanner on input files.
   *
   * This is a standalone scanner, it will print any unmatched
   * text to System.out unchanged.
   *
   * @param argv   the command line, contains the filenames to run
   *               the scanner on.
   */
  public static void main(String[] argv) {
    if (argv.length == 0) {
      System.out.println("Usage : java AnalizadorLexico [ --encoding <name> ] <inputfile(s)>");
    }
    else {
      int firstFilePos = 0;
      String encodingName = "UTF-8";
      if (argv[0].equals("--encoding")) {
        firstFilePos = 2;
        encodingName = argv[1];
        try {
          // Side-effect: is encodingName valid?
          java.nio.charset.Charset.forName(encodingName);
        } catch (Exception e) {
          System.out.println("Invalid encoding '" + encodingName + "'");
          return;
        }
      }
      for (int i = firstFilePos; i < argv.length; i++) {
        AnalizadorLexico scanner = null;
        java.io.FileInputStream stream = null;
        java.io.Reader reader = null;
        try {
          stream = new java.io.FileInputStream(argv[i]);
          reader = new java.io.InputStreamReader(stream, encodingName);
          scanner = new AnalizadorLexico(reader);
          while ( !scanner.zzAtEOF ) scanner.yylex();
        }
        catch (java.io.FileNotFoundException e) {
          System.out.println("File not found : \""+argv[i]+"\"");
        }
        catch (java.io.IOException e) {
          System.out.println("IO error scanning file \""+argv[i]+"\"");
          System.out.println(e);
        }
        catch (Exception e) {
          System.out.println("Unexpected exception:");
          e.printStackTrace();
        }
        finally {
          if (reader != null) {
            try {
              reader.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
          if (stream != null) {
            try {
              stream.close();
            }
            catch (java.io.IOException e) {
              System.out.println("IO error closing file \""+argv[i]+"\"");
              System.out.println(e);
            }
          }
        }
      }
    }
  }


}
